this notebook will explore the behaviour of the data.

In [4]:
import pandas as pd
df = pd.read_csv('../data/raw/sbs_sc_sca_r2$defaultview_linear_2_0.csv') 

df 

#note: drop STRUCTURE, STRUCTURE_ID

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_sb,Economical indicator for structural business statistics,size_emp,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AL,Albania,2019,NaN,502.0,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AL,Albania,2020,NaN,510.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2011,NaN,242.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2012,NaN,238.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2013,NaN,238.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24504,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,M,"Professional, scientific and technical activities",V11110,Enterprises - number,TOTAL,...,UK,United Kingdom,2014,NaN,413222.0,NaN,NaN,NaN,NaN,NaN
24505,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,M,"Professional, scientific and technical activities",V11110,Enterprises - number,TOTAL,...,UK,United Kingdom,2015,NaN,440153.0,NaN,NaN,NaN,NaN,NaN
24506,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,M,"Professional, scientific and technical activities",V11110,Enterprises - number,TOTAL,...,UK,United Kingdom,2016,NaN,478251.0,NaN,b,break in time series,NaN,NaN
24507,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,M,"Professional, scientific and technical activities",V11110,Enterprises - number,TOTAL,...,UK,United Kingdom,2017,NaN,468593.0,NaN,NaN,NaN,NaN,NaN
24508,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,M,"Professional, scientific and technical activities",V11110,Enterprises - number,TOTAL,...,UK,United Kingdom,2018,NaN,470209.0,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df.shape)
print(df.columns.tolist())
df.head(10)

(24509, 21)
['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'nace_r2', 'Statistical classification of economic activities in the European Community (NACE Rev. 2)', 'indic_sb', 'Economical indicator for structural business statistics', 'size_emp', 'Size classes in number of persons employed', 'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG', 'Observation status (Flag) V2 structure', 'CONF_STATUS', 'Confidentiality status (flag)']

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,nace_r2,Statistical classification of economic activities in the European Community (NACE Rev. 2),indic_sb,Economical indicator for structural business statistics,size_emp,...,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AL,Albania,2019,NaN,502.0,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AL,Albania,2020,NaN,510.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2011,NaN,242.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2012,NaN,238.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2013,NaN,238.0,NaN,NaN,NaN,NaN,NaN
5,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2014,NaN,227.0,NaN,NaN,NaN,NaN,NaN
6,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2015,NaN,230.0,NaN,NaN,NaN,NaN,NaN
7,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2016,NaN,226.0,NaN,NaN,NaN,NaN,NaN
8,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2017,NaN,215.0,NaN,NaN,NaN,NaN,NaN
9,dataflow,ESTAT:SBS_SC_SCA_R2$DEFAULTVIEW(1.0),Annual enterprise statistics by size class for...,A,Annual,B,Mining and quarrying,V11110,Enterprises - number,0-9,...,AT,Austria,2018,NaN,192.0,NaN,b,break in time series,NaN,NaN

STRUCTURE                                                                                        str
STRUCTURE_ID                                                                                     str
STRUCTURE_NAME                                                                                   str
freq                                                                                             str
Time frequency                                                                                   str
nace_r2                                                                                          str
Statistical classification of economic activities in the European Community (NACE Rev. 2)        str
indic_sb                                                                                         str
Economical indicator for structural business statistics                                          str
size_emp                                                                                         str
Size classes in number of persons employed                                                       str
geo                                                                                              str
Geopolitical entity (reporting)                                                                  str
TIME_PERIOD                                                                                    int64
Time                                                                                         float64
OBS_VALUE                                                                                    float64
Observation value                                                                            float64
OBS_FLAG                                                                                         str
Observation status (Flag) V2 structure                                                           str
CONF_STATUS                                                                                      str
Confidentiality status (flag)                                                                    str
dtype: object